services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CI=true
    command: >
      sh -c "pnpm install && pnpm dev"
